# Generated by Django 3.0.3 on 2020-02-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0004_auto_20200227_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='focus_citie',
            new_name='focus_cities',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='focus_stock',
            new_name='focus_stocks',
        ),
    ]
