# Generated by Django 3.0.3 on 2020-02-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0005_auto_20200227_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='open_id',
            new_name='openid',
        ),
    ]
