# Generated by Django 3.0.3 on 2020-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0006_auto_20200228_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
