# Generated by Django 3.0.3 on 2020-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0007_auto_20200303_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
