# Generated by Django 3.0.3 on 2020-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0008_auto_20200303_1441'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='emmmm'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='abcde',
        ),
    ]
