publish:
  - app:
        name: 微信
        发布日期: 20180101
        版本: 1.0
  - app:
        name: 支付宝
        发布日期: 20200101
        版本: 1.2
  - app:
        name: 段子
        发布日期: 20200224
        版本: 1.2

developing:
  - a: 你是弟弟
